USE sucos;

-- OS COMANDOS A SEGUIR SÃO EQUIVALENTES
SELECT * FROM tb_produto WHERE PRECO_LISTA BETWEEN 16.007 AND 16.009;
SELECT * FROM tb_produto WHERE PRECO_LISTA >= 16.007 AND PRECO_LISTA <= 16.009;

-- ALGUNS OUTROS EXEMPLOS 
SELECT * FROM tbcliente WHERE IDADE >=18 AND IDADE <= 22;
SELECT * FROM tbcliente WHERE IDADE >=18 AND IDADE <= 22 AND SEXO='M';
SELECT * FROM tbcliente WHERE CIDADE = 'Rio de Janeiro' OR BAIRRO = 'Jardins';
-- SÃO BASICAMENTE OPERAÇÕES DE LÓGICA
SELECT * FROM tbcliente WHERE (IDADE >=18 AND IDADE <= 22 AND SEXO='M') OR (CIDADE = 'Rio de Janeiro' OR BAIRRO = 'Jardins');

-- ESSAS CONDIÇÕES DE FILTRO PODEM SER UTILIZADAS TAMBÉM PARA DELETE E PARA UPDATE

