USE sucos_vendas;

-- AQUI IREMOS VER UM POUCO SOBRE CASE -> BASICAMENTE UM IF
-- LEMBRANDO QUE DEPOIS DO 'END' EU TENHO UM ALIAS

SELECT * FROM tabela_de_produtos;


-- aqui eu segrego prudutos em 3 "classes"
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO ENCONTA'
	ELSE 'PRODUTO BARATO' 
END AS STATUS_PRECO
FROM tabela_de_produtos;


-- aqui eu pegarei as 3 classes segregadas e irei colocar uma média para cada uma delas
SELECT EMBALAGEM,
CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO ENCONTA'
	ELSE 'PRODUTO BARATO' 
END AS STATUS_PRECO, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO
FROM tabela_de_produtos
GROUP BY EMBALAGEM,
CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO ENCONTA'
	ELSE 'PRODUTO BARATO' 
END
ORDER BY PRECO_MEDIO DESC;


-- vou fazer essa comparação somente para produtos com sabor manga
SELECT EMBALAGEM,
CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO ENCONTA'
	ELSE 'PRODUTO BARATO' 
END AS STATUS_PRECO, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO
FROM tabela_de_produtos
WHERE SABOR = 'Manga'
GROUP BY EMBALAGEM,
CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO ENCONTA'
	ELSE 'PRODUTO BARATO' 
END
ORDER BY PRECO_MEDIO DESC;

-- 

SELECT * FROM tabela_de_clientes;
SELECT NOME,
CASE 
	WHEN YEAR(DATA_DE_NASCIMENTO)<1990 THEN 'VELHO'
    WHEN YEAR(DATA_DE_NASCIMENTO)>= 1990 AND YEAR(DATA_DE_NASCIMENTO)< 1995 THEN 'JOVEN'
    ELSE 'CRIANCA'
END AS LIFE_STATUS
FROM tabela_de_clientes
ORDER BY YEAR(DATA_DE_NASCIMENTO) DESC;

