-- AGORA FAREMOS ALGUNS TESTES COM FUNÇÕES MATEMÁTICAS

-- OPERAÇÕES MATEMÁTICAS
SELECT (23+((25-2)/2)*45) AS RESULTADO;

-- CEILING -> ARREDONDAMENTO
SELECT CEILING(12.3333332) AS RESULTADO;

-- ROUND -> ARREDONDAMENTO OU TRUNCAMENTO
SELECT ROUND(12.3333332) AS RESULTADO;
SELECT ROUND(12.77777) AS RESULTADO;

-- FLOOR -> TRUNCAMENTO
SELECT FLOOR(12.77777) AS RESULTADO;

-- NÚMERO ALEATÓRIO ENTRE 0 E 1
SELECT RAND() AS RESULTADO;

-- FATURAMENTO
SELECT NUMERO, QUANTIDADE, PRECO, QUANTIDADE*PRECO AS FATURAMENTO FROM itens_notas_fiscais;
SELECT NUMERO, QUANTIDADE, PRECO, ROUND(QUANTIDADE*PRECO, 2) AS FATURAMENTO FROM itens_notas_fiscais;

-- ///////////////////
SELECT * FROM notas_fiscais;
SELECT * FROM itens_notas_fiscais;


SELECT A.NOME_DO_PRODUTO, A.EMBALAGEM, A.PRECO_DE_LISTA, X.MAIOR_PRECO	
FROM (tabela_de_produtos AS A) INNER JOIN (vw_maiores_embalagens AS X)
ON A.EMBALAGEM = X.EMBALAGEM;


-- verificar faturamento liquido, bruto e impostos
SELECT 
YEAR(A.DATA_VENDA) AS ANO, 
ROUND(SUM(B.QUANTIDADE * B.PRECO), 2) AS FATURAMENTO_BRUTO,
ROUND(SUM(B.QUANTIDADE * B.PRECO * A.IMPOSTO), 2) AS IMPOSTO_,
ROUND(SUM(B.QUANTIDADE * B.PRECO * (1 - A.IMPOSTO)), 2) AS FATURAMENTO_LIQUIDO
FROM (notas_fiscais AS A) INNER JOIN (itens_notas_fiscais as B)
ON A.NUMERO = B.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
ORDER BY YEAR(DATA_VENDA);
