USE sucos_vendas;
-- JOIN -> POSSIBLIDADE DE UNIRMOS 2 OU MAIS TABELAS ATRAVÉS DE CAMPOS EM COMUM
-- INNER JOIN -> RETORNA SOMENTE QUANDO TEMOS CHAVES CORRESPONDENTES
-- LEFT JOIN -> RETORNA TODOS DA TABELA DA ESQUERDA E SOMENTE OS CORRESPONDENTES DA DIREITA
-- RIGHT JOIN -> RETORNA SOMENTE OS CORRESPONDENTES DA ESQUERDA E TODOS DA DIREITA
-- FULL JOIN -> VAI JUNTAR TUDO E MANTER TUDO, QUEM NÃO TIVER CORRESPONDENTE GANHARÁ UM NULL NO LADO OPOSTO DA TABELA
-- CROSS JOIN -> RETORNA UM PRODUTO CARTESIANO DE TODAS AS RELAÇÕES
-- QUANDO NÃO HÁ CORRESPONDÊNCIA TEMOS UM CAMPO NULO

SELECT * FROM tabela_de_vendedores;
SELECT * FROM notas_fiscais;

-- nesse caso o campo em comum entre as duas tabelas é o matrícula

SELECT * FROM tabela_de_vendedores A 
INNER JOIN notas_fiscais B
ON A.MATRICULA = B.MATRICULA;

-- OS 2 CÓDIGOS ABAIXO SÃO CORRESPONDENTES, TODAVIA O PRIMEIRO É MAIS ATUAL
-- AQUI TEMOS UM INNER JOIN TRADICIONAL
SELECT A.MATRICULA, A.NOME, COUNT(*) FROM
tabela_de_vendedores A 
INNER JOIN notas_fiscais B
ON A.MATRICULA = B.MATRICULA
GROUP BY A.MATRICULA, A.NOME;

-- AQUI TEMOS UM CROSSJOIN COM UM CONDICIONAL WHERE -- DAS ANTIGAS
SELECT A.MATRICULA, A.NOME, COUNT(*) FROM
tabela_de_vendedores A , notas_fiscais B
WHERE A.MATRICULA = B.MATRICULA
GROUP BY A.MATRICULA, A.NOME;


--  //////////////////////////////////////////
SELECT * FROM notas_fiscais;
SELECT * FROM itens_notas_fiscais;


SELECT YEAR(DATA_VENDA) AS ANO, SUM(QUANTIDADE * PRECO) AS FATURAMENTO 
FROM notas_fiscais NF 
INNER JOIN itens_notas_fiscais INF
ON NF.NUMERO = INF.NUMERO
GROUP BY ANO;
