use sucos_vendas;

-- Aqui iremos aprender subconsultas
-- Basicamente uma identação de consultas


-- BAIRROS DOS VENDEDORES
SELECT DISTINCT BAIRRO FROM tabela_de_vendedores;

-- ESCOLHENDO ONDE HÁ UMA COINCIDÊNCIA ENTRE OS BAIRROS DOS CLIENTES E VENDEDORES 
-- DE ACORDO COM A INFORAMAÇÃO DO CÓDIGO ACIMA 

-- FORMA MAIS MANUAL
SELECT * FROM tabela_de_clientes WHERE BAIRRO IN ('Tijuca', 'Jardins', 'Copacabana', 'Santo Amaro');


-- FORMA MAIS AUTOMÁTICA
SELECT * FROM tabela_de_clientes WHERE BAIRRO IN (SELECT DISTINCT BAIRRO FROM tabela_de_vendedores);


-- MAIS UM EXEMPLO
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) FROM tabela_de_produtos 
GROUP BY EMBALAGEM;

-- QUAIS SÃO AS EMBALAGENS CUJO MAIOR PREÇO É MAIOR QUE 10
SELECT X.EMBALAGEM, X.PRECO_MAXIMO FROM
(SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAXIMO FROM tabela_de_produtos 
GROUP BY EMBALAGEM) AS X WHERE X.PRECO_MAXIMO >= 10;

-- ////////////////////////////////
SELECT X.CPF, X.CONTAGEM FROM 
(SELECT CPF, COUNT(*) AS CONTAGEM FROM notas_fiscais WHERE YEAR(DATA_VENDA) = 2016
GROUP BY CPF) AS X WHERE X.CONTAGEM > 2000;
