USE suco_vendas;

-- O LIKE É UTILIZADO PARA PEGAR PARTE ESPECÍFICA DE UMA STRING DENTRO DE UMA COLUNA
-- SENDO '%ALGO%' GENERALISTA E '%ALGO' PEGANDO SOMENTE DO FIM DA FRASE

-- USO DO LIKE 
SELECT * FROM tabela_de_produtos WHERE SABOR LIKE '%MACÃ%';
SELECT * FROM tabela_de_produtos WHERE (SABOR LIKE '%MACÃ%' AND EMBALAGEM = 'PET');

SELECT * FROM tabela_de_clientes WHERE NOME LIKE '%MATTOS';