USE sucos;

-- CLIENTE COM 22 ANOS
SELECT * FROM tbcliente WHERE IDADE = 22;

-- CLIENTE COM MAIS DE 22 ANOS
SELECT * FROM tbcliente WHERE IDADE > 22;

-- CLIENTES COM MENOS DE 22 ANOS
SELECT * FROM tbcliente WHERE IDADE < 22;

-- CLIENTE COM 22 ANOS OU MAIS 
SELECT * FROM tbcliente WHERE IDADE >= 22;

-- CLIENTE COM 22 ANOS OU MENOS
SELECT * FROM tbcliente WHERE IDADE <= 22;

-- CLIENTES DE TODAS AS IDADES EXCETO AQUELES COM 22 ANOS
SELECT * FROM tbcliente WHERE IDADE <> 22;

-- SELECIONAR CLIENTES A PARTIR DE UMA ORDEM ALFABÉTICA ESPECÍFICA - de Fernando para cima
SELECT * FROM tbcliente WHERE NOME > 'Fernando Cavalcante';

-- SELECIONAR CLIENTES A PARTIR DE UMA ORDEM ALFABÉTICA ESPECÍFICA - de Fernando para baixo
SELECT * FROM tbcliente WHERE NOME < 'Fernando Cavalcante';

-- SELECIONAR CLIENTES A PARTIR DE UMA ORDEM ALFABÉTICA ESPECÍFICA - com o Fernando para baixo
SELECT * FROM tbcliente WHERE NOME <= 'Fernando Cavalcante';

-- SELECIONAR CLIENTES A PARTIR DE UMA ORDEM ALFABÉTICA ESPECÍFICA - todos menos o fernando
SELECT * FROM tbcliente WHERE NOME <> 'Fernando Cavalcante';

-- FILTROS EM PONTOS FLUTUANTES NÃO CONSEGUEM FAZER IGUALDADES(=) ou DESIGUALDADES (<>)
-- E COMPOSTOS COMO (<= OU >= ) 
SELECT * FROM tb_produto WHERE PRECO_LISTA > 16.008;
SELECT * FROM tb_produto WHERE PRECO_LISTA < 16.008;

-- ESSA MANEIRA É UMA DAS MAIS EFICIENTES QUANDO PRECISAMOS SELCIONAR O NÚMERO FLUTUANTE EM ESPECÍFICO 
SELECT * FROM tb_produto WHERE PRECO_LISTA BETWEEN 16.007 AND 16.009;

